# Generated by Django 5.2 on 2025-04-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='test_correct_answer',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='test_question',
        ),
        migrations.AddField(
            model_name='lesson',
            name='html_expected_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='html_task_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='task_type',
            field=models.CharField(choices=[('none', 'Нет задания'), ('test', 'Тест'), ('html', 'HTML/JS задание')], default='none', max_length=10),
        ),
    ]
