# Generated by Django 5.2 on 2025-04-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coursesubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseSubscription',
        ),
    ]
