# Generated by Django 5.2 on 2025-04-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_used_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('HTML', 'HTML'), ('Python', 'Python'), ('Go', 'Go')], default='HTML', max_length=50),
        ),
    ]
