# Generated by Django 5.2 on 2025-04-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('HTML', 'HTML'), ('Go', 'Go'), ('Python', 'Python')], default='HTML', max_length=20),
        ),
    ]
